name: Release
on:
  push:
    branches:
      - main
      - feature/pipeline
    paths:
      - "**.md"
      - "mkdocs.yml"
  workflow_dispatch:
  
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Python
        uses: actions/setup-python@v2
      - name: Install Poetry Package 
        run: |
          pip install --upgrade pip
          pip install poetry mkdocs mkdocs-gen-files
      - name: Install Dependencies
        run: poetry install --with docs
      - name: Set User
        run: git config user.name 'github-actions[bot]' && git config user.email 'github-actions[bot]@users.noreply.github.com'
      - name: Publish docs
        run: mkdocs gh-deploy