
name: PyPi 

on:
  push:
    branches: 
        - main
        - pypi-pipeline
  release:
    types: [published]
  workflow_dispatch:

concurrency:
  group: "release"
  cancel-in-progress: false

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' 
      - name: Install Poetry Package 
        run: |
          pip install --upgrade pip
          pip install poetry pytest pytest-cov
          poetry install 
      - name: Test with pytest
        continue-on-error: true
        run: |
            pytest
  build:
    name: Build
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' 
      - name: Install Poetry Package 
        run: |
          pip install --upgrade pip
          pip install build
      - name: Build package
        run: python -m build